FROM golang:1.21

RUN apt update && apt install \
  ca-certificates \
  git \
  make

WORKDIR $GOPATH/src/github.com/axelarnetwork/axelar-core
ARG SEMVER
ARG WASM=true

COPY ./go.mod .
COPY ./go.sum .
RUN go mod download

COPY . .
ENV CGO_ENABLED=1
RUN make build-binaries
