FROM golang:1.19

RUN apt update && apt install \
  ca-certificates \
  git \
  make

WORKDIR $GOPATH/src/github.com/axelarnetwork/axelar-core
ARG SEMVER

COPY ./go.mod .
COPY ./go.sum .
RUN go mod download

COPY . .
ENV CGO_ENABLED=0
RUN make build-binaries
