FROM golang:1.16

RUN apt update && apt install \
  openssh-client \
  git \
  ca-certificates \
  make

WORKDIR $GOPATH/src/github.com/axelarnetwork/axelar-core
ARG SEMVER

RUN git config --global url."git@github.com:axelarnetwork".insteadOf https://github.com/axelarnetwork
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

COPY ./go.mod .
COPY ./go.sum .
RUN --mount=type=ssh go mod download

COPY . .
ENV CGO_ENABLED=0
RUN make build-binaries