# syntax=docker/dockerfile:experimental

FROM tendermintdev/sdk-proto-gen:v0.1 as build

RUN apk add --no-cache --update \
  git \
  ca-certificates

WORKDIR /workspace

COPY ./go.mod .
COPY ./go.sum .

RUN go mod download
RUN go get github.com/regen-network/cosmos-proto/protoc-gen-gocosmos@latest
