# syntax=docker/dockerfile:experimental

FROM golang:1.15 as debug

WORKDIR axelar

RUN go get github.com/go-delve/delve/cmd/dlv

RUN git config --global url."git@github.com:axelarnetwork".insteadOf https://github.com/axelarnetwork
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

COPY ./go.mod .
COPY ./go.sum .
RUN --mount=type=ssh go mod download

COPY . .
RUN make debug
RUN cp /go/axelar/bin/axelar* /root/
ENV PATH="/root:${PATH}"
