// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitcoin/v1beta1/types.proto

package types

import (
	fmt "fmt"
	exported "github.com/axelarnetwork/axelar-core/x/tss/exported"
	github_com_btcsuite_btcutil "github.com/btcsuite/btcutil"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AddressRole int32

const (
	None          AddressRole = 0
	Deposit       AddressRole = 1
	Consolidation AddressRole = 2
)

var AddressRole_name = map[int32]string{
	0: "ADDRESS_ROLE_UNSPECIFIED",
	1: "ADDRESS_ROLE_DEPOSIT",
	2: "ADDRESS_ROLE_CONSOLIDATION",
}

var AddressRole_value = map[string]int32{
	"ADDRESS_ROLE_UNSPECIFIED":   0,
	"ADDRESS_ROLE_DEPOSIT":       1,
	"ADDRESS_ROLE_CONSOLIDATION": 2,
}

func (x AddressRole) String() string {
	return proto.EnumName(AddressRole_name, int32(x))
}

func (AddressRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ca561ce6167cd5e4, []int{0}
}

type SignState int32

const (
	SIGN_STATE_UNSPECIFIED SignState = 0
	Signing                SignState = 1
	Signed                 SignState = 2
	Ready                  SignState = 3
)

var SignState_name = map[int32]string{
	0: "SIGN_STATE_UNSPECIFIED",
	1: "SIGN_STATE_SIGNING_PENDING_TRANSFERS",
	2: "SIGN_STATE_SIGNED_NOT_CONFIRMED",
	3: "SIGN_STATE_READY_TO_SIGN",
}

var SignState_value = map[string]int32{
	"SIGN_STATE_UNSPECIFIED":               0,
	"SIGN_STATE_SIGNING_PENDING_TRANSFERS": 1,
	"SIGN_STATE_SIGNED_NOT_CONFIRMED":      2,
	"SIGN_STATE_READY_TO_SIGN":             3,
}

func (x SignState) String() string {
	return proto.EnumName(SignState_name, int32(x))
}

func (SignState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ca561ce6167cd5e4, []int{1}
}

type Transaction struct {
	Tx            []byte           `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	AssignNextKey bool             `protobuf:"varint,2,opt,name=assign_next_key,json=assignNextKey,proto3" json:"assign_next_key,omitempty"`
	NextKeyRole   exported.KeyRole `protobuf:"varint,3,opt,name=next_key_role,json=nextKeyRole,proto3,enum=tss.exported.v1beta1.KeyRole" json:"next_key_role,omitempty"`
	NextKeyID     string           `protobuf:"bytes,4,opt,name=next_key_id,json=nextKeyId,proto3" json:"next_key_id,omitempty"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca561ce6167cd5e4, []int{0}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return m.Size()
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

// OutPointInfo describes all the necessary information to confirm the outPoint
// of a transaction
type OutPointInfo struct {
	OutPoint string                             `protobuf:"bytes,1,opt,name=out_point,json=outPoint,proto3" json:"out_point,omitempty"`
	Amount   github_com_btcsuite_btcutil.Amount `protobuf:"varint,2,opt,name=amount,proto3,casttype=github.com/btcsuite/btcutil.Amount" json:"amount,omitempty"`
	Address  string                             `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *OutPointInfo) Reset()      { *m = OutPointInfo{} }
func (*OutPointInfo) ProtoMessage() {}
func (*OutPointInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca561ce6167cd5e4, []int{1}
}
func (m *OutPointInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OutPointInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OutPointInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OutPointInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutPointInfo.Merge(m, src)
}
func (m *OutPointInfo) XXX_Size() int {
	return m.Size()
}
func (m *OutPointInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OutPointInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OutPointInfo proto.InternalMessageInfo

// AddressInfo is a wrapper containing the Bitcoin P2WSH address, it's
// corresponding script and the underlying key
type AddressInfo struct {
	Address      string      `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Role         AddressRole `protobuf:"varint,2,opt,name=role,proto3,enum=bitcoin.v1beta1.AddressRole" json:"role,omitempty"`
	RedeemScript []byte      `protobuf:"bytes,3,opt,name=redeem_script,json=redeemScript,proto3" json:"redeem_script,omitempty"`
	KeyID        string      `protobuf:"bytes,4,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	MaxSigCount  uint32      `protobuf:"varint,5,opt,name=max_sig_count,json=maxSigCount,proto3" json:"max_sig_count,omitempty"`
}

func (m *AddressInfo) Reset()         { *m = AddressInfo{} }
func (m *AddressInfo) String() string { return proto.CompactTextString(m) }
func (*AddressInfo) ProtoMessage()    {}
func (*AddressInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca561ce6167cd5e4, []int{2}
}
func (m *AddressInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddressInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddressInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddressInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressInfo.Merge(m, src)
}
func (m *AddressInfo) XXX_Size() int {
	return m.Size()
}
func (m *AddressInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AddressInfo proto.InternalMessageInfo

type Network struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *Network) Reset()         { *m = Network{} }
func (m *Network) String() string { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()    {}
func (*Network) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca561ce6167cd5e4, []int{3}
}
func (m *Network) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Network.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Network) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Network.Merge(m, src)
}
func (m *Network) XXX_Size() int {
	return m.Size()
}
func (m *Network) XXX_DiscardUnknown() {
	xxx_messageInfo_Network.DiscardUnknown(m)
}

var xxx_messageInfo_Network proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("bitcoin.v1beta1.AddressRole", AddressRole_name, AddressRole_value)
	proto.RegisterEnum("bitcoin.v1beta1.SignState", SignState_name, SignState_value)
	proto.RegisterType((*Transaction)(nil), "bitcoin.v1beta1.Transaction")
	proto.RegisterType((*OutPointInfo)(nil), "bitcoin.v1beta1.OutPointInfo")
	proto.RegisterType((*AddressInfo)(nil), "bitcoin.v1beta1.AddressInfo")
	proto.RegisterType((*Network)(nil), "bitcoin.v1beta1.Network")
}

func init() { proto.RegisterFile("bitcoin/v1beta1/types.proto", fileDescriptor_ca561ce6167cd5e4) }

var fileDescriptor_ca561ce6167cd5e4 = []byte{
	// 739 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xbf, 0x8f, 0xe3, 0x44,
	0x14, 0xce, 0x64, 0x93, 0x6c, 0x3c, 0x49, 0xee, 0xc2, 0xe8, 0x84, 0x22, 0x1f, 0xe7, 0x58, 0x01,
	0x96, 0xe8, 0xa4, 0xb3, 0x59, 0x7e, 0x34, 0x14, 0x48, 0xde, 0xd8, 0x7b, 0xb2, 0xee, 0xb0, 0xa3,
	0xb1, 0x29, 0xa0, 0xb1, 0x9c, 0x78, 0x30, 0xa3, 0x4d, 0x3c, 0x91, 0x3d, 0x01, 0xe7, 0x3f, 0x40,
	0xa1, 0xa1, 0x84, 0x22, 0x12, 0x12, 0x14, 0xfc, 0x07, 0xf4, 0x88, 0xe2, 0xca, 0x2d, 0xa9, 0x56,
	0x90, 0xfd, 0x2f, 0xa8, 0x90, 0x27, 0x0e, 0x9b, 0xac, 0xae, 0xca, 0x9b, 0xf7, 0xbe, 0xef, 0xe5,
	0x7b, 0xdf, 0x9b, 0x31, 0x7c, 0x3c, 0xa1, 0x7c, 0xca, 0x68, 0xa2, 0x7f, 0x73, 0x3e, 0x21, 0x3c,
	0x3c, 0xd7, 0xf9, 0x6a, 0x41, 0x32, 0x6d, 0x91, 0x32, 0xce, 0xd0, 0xc3, 0xb2, 0xa8, 0x95, 0x45,
	0xf9, 0x51, 0xcc, 0x62, 0x26, 0x6a, 0x7a, 0x11, 0xed, 0x60, 0xb2, 0xca, 0xb3, 0x4c, 0x27, 0xf9,
	0x82, 0xa5, 0x9c, 0x44, 0xaf, 0x6b, 0x34, 0xf8, 0x1d, 0xc0, 0x96, 0x9f, 0x86, 0x49, 0x16, 0x4e,
	0x39, 0x65, 0x09, 0x7a, 0x00, 0xab, 0x3c, 0xef, 0x01, 0x15, 0x0c, 0xdb, 0xb8, 0xca, 0x73, 0x74,
	0x06, 0x1f, 0x86, 0x59, 0x46, 0xe3, 0x24, 0x48, 0x48, 0xce, 0x83, 0x2b, 0xb2, 0xea, 0x55, 0x55,
	0x30, 0x6c, 0xe2, 0xce, 0x2e, 0xed, 0x90, 0x9c, 0xbf, 0x20, 0x2b, 0x64, 0xc0, 0xce, 0x1e, 0x10,
	0xa4, 0x6c, 0x46, 0x7a, 0x27, 0x2a, 0x18, 0x3e, 0xf8, 0xe0, 0x89, 0xc6, 0xb3, 0x4c, 0xdb, 0x2b,
	0xd8, 0xab, 0xd5, 0x5e, 0x90, 0x15, 0x66, 0x33, 0x82, 0x5b, 0xc9, 0x8e, 0x5e, 0x1c, 0xd0, 0x33,
	0xd8, 0xfa, 0xbf, 0x05, 0x8d, 0x7a, 0x35, 0x15, 0x0c, 0xa5, 0x8b, 0xce, 0xf6, 0xa6, 0x2f, 0x95,
	0x7f, 0x62, 0x9b, 0x58, 0x2a, 0x09, 0x76, 0x34, 0xf8, 0x1e, 0xc0, 0xb6, 0xbb, 0xe4, 0x63, 0x46,
	0x13, 0x6e, 0x27, 0x5f, 0x31, 0xf4, 0x18, 0x4a, 0x6c, 0xc9, 0x83, 0x45, 0x91, 0x10, 0x13, 0x48,
	0xb8, 0xc9, 0x4a, 0x00, 0xfa, 0x14, 0x36, 0xc2, 0x39, 0x5b, 0x26, 0x5c, 0xc8, 0x3f, 0xb9, 0x38,
	0xfb, 0xf7, 0xa6, 0x3f, 0x88, 0x29, 0xff, 0x7a, 0x39, 0xd1, 0xa6, 0x6c, 0xae, 0x4f, 0xf8, 0x34,
	0x5b, 0x52, 0x4e, 0x8a, 0x60, 0xc9, 0xe9, 0x4c, 0x33, 0x04, 0x1a, 0x97, 0x2c, 0xd4, 0x83, 0xa7,
	0x61, 0x14, 0xa5, 0x24, 0xcb, 0xc4, 0x64, 0x12, 0xde, 0x1f, 0x3f, 0xa9, 0xfd, 0xf8, 0x73, 0xbf,
	0x32, 0xf8, 0x13, 0xc0, 0x96, 0xb1, 0xcb, 0x08, 0x31, 0x07, 0x78, 0x70, 0x84, 0x47, 0xef, 0xc3,
	0x9a, 0x30, 0xa8, 0x2a, 0x0c, 0x7a, 0x4b, 0xbb, 0xb7, 0x49, 0xad, 0xec, 0x22, 0xfc, 0x11, 0x48,
	0xf4, 0x36, 0xec, 0xa4, 0x24, 0x22, 0x64, 0x1e, 0x64, 0xd3, 0x94, 0x2e, 0xb8, 0x50, 0xd0, 0xc6,
	0xed, 0x5d, 0xd2, 0x13, 0x39, 0xa4, 0xc2, 0xc6, 0x91, 0x71, 0xd2, 0xf6, 0xa6, 0x5f, 0xdf, 0x99,
	0x56, 0xbf, 0x2a, 0x0c, 0x43, 0x03, 0xd8, 0x99, 0x87, 0x79, 0x90, 0xd1, 0x38, 0x98, 0x0a, 0x27,
	0xea, 0x2a, 0x18, 0x76, 0x70, 0x6b, 0x1e, 0xe6, 0x1e, 0x8d, 0x47, 0x45, 0x6a, 0xf0, 0x04, 0x9e,
	0x3a, 0x84, 0x7f, 0xcb, 0xd2, 0x2b, 0x84, 0x60, 0x2d, 0x09, 0xe7, 0xa4, 0x94, 0x2f, 0xe2, 0xa7,
	0x3f, 0xdd, 0x4d, 0x29, 0x56, 0x76, 0x06, 0x7b, 0x86, 0x69, 0x62, 0xcb, 0xf3, 0x02, 0xec, 0xbe,
	0xb4, 0x82, 0xcf, 0x1d, 0x6f, 0x6c, 0x8d, 0xec, 0x4b, 0xdb, 0x32, 0xbb, 0x15, 0xb9, 0xb9, 0xde,
	0xa8, 0x35, 0x87, 0x25, 0x04, 0xbd, 0x0b, 0x1f, 0x1d, 0xe1, 0x4c, 0x6b, 0xec, 0x7a, 0xb6, 0xdf,
	0x05, 0x72, 0x6b, 0xbd, 0x51, 0x4f, 0x4d, 0xb2, 0x60, 0x19, 0xe5, 0xe8, 0x1c, 0xca, 0x47, 0xb0,
	0x91, 0xeb, 0x78, 0xee, 0x4b, 0xdb, 0x34, 0x7c, 0xdb, 0x75, 0xba, 0x55, 0xf9, 0x8d, 0xf5, 0x46,
	0xed, 0x8c, 0x58, 0x92, 0xb1, 0x19, 0x8d, 0xc2, 0xe2, 0xbe, 0xca, 0xcd, 0xef, 0x7e, 0x51, 0x2a,
	0xbf, 0xfd, 0xaa, 0x80, 0xa7, 0x7f, 0x00, 0x28, 0x79, 0x34, 0x4e, 0x3c, 0x1e, 0x72, 0x82, 0x64,
	0xf8, 0xa6, 0x67, 0x3f, 0x77, 0x02, 0xcf, 0x37, 0xfc, 0x7b, 0xba, 0xd0, 0xc7, 0xf0, 0x9d, 0x83,
	0x5a, 0x11, 0xda, 0xce, 0xf3, 0x60, 0x6c, 0x39, 0x66, 0xf1, 0xeb, 0x63, 0xc3, 0xf1, 0x2e, 0x2d,
	0xec, 0xed, 0xd5, 0x15, 0x4d, 0x69, 0x12, 0x23, 0x1d, 0xf6, 0xef, 0xd1, 0x2c, 0x33, 0x70, 0x5c,
	0xbf, 0x90, 0x79, 0x69, 0xe3, 0xcf, 0x2c, 0xb3, 0x5b, 0x95, 0xe1, 0x7a, 0xa3, 0x36, 0x0a, 0x06,
	0x89, 0xd0, 0x7b, 0xb0, 0x77, 0x40, 0xc0, 0x96, 0x61, 0x7e, 0x11, 0xf8, 0xae, 0x60, 0x76, 0x4f,
	0x64, 0x69, 0xbd, 0x51, 0xeb, 0x98, 0x84, 0xd1, 0xea, 0x6e, 0x88, 0x0b, 0xfc, 0xea, 0x1f, 0xa5,
	0xf2, 0x6a, 0xab, 0x80, 0xeb, 0xad, 0x02, 0xfe, 0xde, 0x2a, 0xe0, 0x87, 0x5b, 0xa5, 0x72, 0x7d,
	0xab, 0x54, 0xfe, 0xba, 0x55, 0x2a, 0x5f, 0x7e, 0x74, 0x70, 0x61, 0xc3, 0x9c, 0xcc, 0xc2, 0x34,
	0xd9, 0x2d, 0xab, 0x3c, 0x3d, 0x9b, 0xb2, 0x94, 0xe8, 0xb9, 0xbe, 0xff, 0x72, 0x88, 0x87, 0x3e,
	0x69, 0x88, 0x97, 0xfe, 0xe1, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x5f, 0x54, 0xbf, 0x51,
	0x04, 0x00, 0x00,
}

func (m *Transaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Transaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Transaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NextKeyID) > 0 {
		i -= len(m.NextKeyID)
		copy(dAtA[i:], m.NextKeyID)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.NextKeyID)))
		i--
		dAtA[i] = 0x22
	}
	if m.NextKeyRole != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.NextKeyRole))
		i--
		dAtA[i] = 0x18
	}
	if m.AssignNextKey {
		i--
		if m.AssignNextKey {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Tx) > 0 {
		i -= len(m.Tx)
		copy(dAtA[i:], m.Tx)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Tx)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OutPointInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OutPointInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OutPointInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Amount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.OutPoint) > 0 {
		i -= len(m.OutPoint)
		copy(dAtA[i:], m.OutPoint)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OutPoint)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AddressInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddressInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AddressInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxSigCount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxSigCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.KeyID) > 0 {
		i -= len(m.KeyID)
		copy(dAtA[i:], m.KeyID)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.KeyID)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.RedeemScript) > 0 {
		i -= len(m.RedeemScript)
		copy(dAtA[i:], m.RedeemScript)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RedeemScript)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Role != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Role))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Network) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Network) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Network) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Transaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Tx)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.AssignNextKey {
		n += 2
	}
	if m.NextKeyRole != 0 {
		n += 1 + sovTypes(uint64(m.NextKeyRole))
	}
	l = len(m.NextKeyID)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *OutPointInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OutPoint)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTypes(uint64(m.Amount))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *AddressInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Role != 0 {
		n += 1 + sovTypes(uint64(m.Role))
	}
	l = len(m.RedeemScript)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.KeyID)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.MaxSigCount != 0 {
		n += 1 + sovTypes(uint64(m.MaxSigCount))
	}
	return n
}

func (m *Network) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Transaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Transaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Transaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tx = append(m.Tx[:0], dAtA[iNdEx:postIndex]...)
			if m.Tx == nil {
				m.Tx = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssignNextKey", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AssignNextKey = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextKeyRole", wireType)
			}
			m.NextKeyRole = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextKeyRole |= exported.KeyRole(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextKeyID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NextKeyID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OutPointInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OutPointInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OutPointInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutPoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutPoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= github_com_btcsuite_btcutil.Amount(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddressInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddressInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddressInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Role", wireType)
			}
			m.Role = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Role |= AddressRole(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedeemScript", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RedeemScript = append(m.RedeemScript[:0], dAtA[iNdEx:postIndex]...)
			if m.RedeemScript == nil {
				m.RedeemScript = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSigCount", wireType)
			}
			m.MaxSigCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSigCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Network) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Network: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Network: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
