// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: axelar/axelarnet/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	utils "github.com/axelarnetwork/axelar-core/utils"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	Params           Params                                        `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	CollectorAddress github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,2,opt,name=collector_address,json=collectorAddress,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"collector_address,omitempty"`
	Chains           []CosmosChain                                 `protobuf:"bytes,3,rep,name=chains,proto3" json:"chains"`
	TransferQueue    utils.QueueState                              `protobuf:"bytes,5,opt,name=transfer_queue,json=transferQueue,proto3" json:"transfer_queue"`
	FailedTransfers  []IBCTransfer                                 `protobuf:"bytes,6,rep,name=failed_transfers,json=failedTransfers,proto3" json:"failed_transfers"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_66d88d9f35b1824e, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GenesisState)(nil), "axelar.axelarnet.v1beta1.GenesisState")
}

func init() {
	proto.RegisterFile("axelar/axelarnet/v1beta1/genesis.proto", fileDescriptor_66d88d9f35b1824e)
}

var fileDescriptor_66d88d9f35b1824e = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x6e, 0xda, 0x30,
	0x1c, 0xc6, 0x93, 0x01, 0xd1, 0x14, 0xd8, 0xc6, 0xa2, 0x1d, 0x22, 0x0e, 0x21, 0x9b, 0xc6, 0xc4,
	0x85, 0x44, 0x30, 0x69, 0xc7, 0x49, 0x24, 0x87, 0xaa, 0x95, 0x2a, 0xb5, 0x14, 0xf5, 0xd0, 0x43,
	0x91, 0x71, 0x4c, 0x88, 0x08, 0x31, 0xb5, 0x9d, 0x96, 0xbe, 0x45, 0x1f, 0xa1, 0x8f, 0xc3, 0x91,
	0x63, 0x4f, 0xa8, 0x85, 0xb7, 0xe8, 0xa9, 0xc2, 0x76, 0x22, 0x7a, 0x88, 0x7a, 0x72, 0xf2, 0xcf,
	0xef, 0xfb, 0xfc, 0xf9, 0x8b, 0xf5, 0x3f, 0x60, 0x89, 0x62, 0x40, 0x5c, 0xb1, 0x24, 0x88, 0xb9,
	0xb7, 0xdd, 0x31, 0x62, 0xa0, 0xeb, 0x86, 0x28, 0x41, 0x34, 0xa2, 0xce, 0x82, 0x60, 0x86, 0x0d,
	0x53, 0x00, 0x4e, 0xce, 0x39, 0x92, 0x6b, 0xfc, 0x08, 0x71, 0x88, 0x39, 0xe4, 0xee, 0x9f, 0x04,
	0xdf, 0x68, 0x15, 0xfa, 0x2e, 0x00, 0x01, 0x73, 0x69, 0xdb, 0xf8, 0x5d, 0x88, 0xb1, 0xfb, 0x05,
	0xca, 0xa8, 0x9f, 0x92, 0x4a, 0x59, 0x14, 0xd3, 0x9c, 0xb8, 0x49, 0x51, 0x8a, 0x88, 0x40, 0x7e,
	0x3d, 0x96, 0xf4, 0xda, 0x91, 0x48, 0x7c, 0xc1, 0x00, 0x43, 0xc6, 0x7f, 0x5d, 0x13, 0x3b, 0x99,
	0xaa, 0xad, 0xb6, 0xab, 0x3d, 0xdb, 0x29, 0x3a, 0x81, 0x73, 0xc6, 0x39, 0xaf, 0xbc, 0xda, 0x34,
	0x95, 0x81, 0x54, 0x19, 0xd7, 0xfa, 0x77, 0x88, 0xe3, 0x18, 0x41, 0x86, 0xc9, 0x08, 0x04, 0x01,
	0x41, 0x94, 0x9a, 0x9f, 0x6c, 0xb5, 0x5d, 0xf3, 0xba, 0xaf, 0x9b, 0x66, 0x27, 0x8c, 0xd8, 0x34,
	0x1d, 0x3b, 0x10, 0xcf, 0x5d, 0x88, 0xe9, 0x1c, 0x53, 0xb9, 0x74, 0x68, 0x30, 0x93, 0xe1, 0xfb,
	0x10, 0xf6, 0x85, 0x70, 0x50, 0xcf, 0xbd, 0xe4, 0xc4, 0xf0, 0x75, 0x0d, 0x4e, 0x41, 0x94, 0x50,
	0xb3, 0x64, 0x97, 0xda, 0xd5, 0x5e, 0xab, 0x38, 0x9f, 0xcf, 0x8d, 0xfd, 0x3d, 0x9d, 0x85, 0x14,
	0x52, 0xe3, 0x54, 0xff, 0xca, 0x08, 0x48, 0xe8, 0x04, 0x91, 0x11, 0xaf, 0xc3, 0xac, 0xbc, 0x3f,
	0x2c, 0x6f, 0x2c, 0x37, 0x3a, 0xdf, 0x23, 0xbc, 0x1e, 0xe9, 0xf3, 0x25, 0x53, 0xf3, 0x2f, 0xc6,
	0xa5, 0x5e, 0x9f, 0x80, 0x28, 0x46, 0xc1, 0x28, 0x9b, 0x53, 0x53, 0xfb, 0x28, 0xdd, 0xb1, 0xe7,
	0x0f, 0x25, 0x2d, 0x5d, 0xbf, 0x09, 0x93, 0x6c, 0x4a, 0x4f, 0xca, 0x9f, 0xcb, 0xf5, 0x8a, 0x37,
	0x5c, 0xbd, 0x58, 0xca, 0x6a, 0x6b, 0xa9, 0xeb, 0xad, 0xa5, 0x3e, 0x6f, 0x2d, 0xf5, 0x61, 0x67,
	0x29, 0xeb, 0x9d, 0xa5, 0x3c, 0xed, 0x2c, 0xe5, 0xea, 0xdf, 0x41, 0xa1, 0xf9, 0x26, 0x77, 0x98,
	0xcc, 0xe4, 0x5b, 0x07, 0x62, 0x82, 0xdc, 0xe5, 0xc1, 0x4d, 0xe1, 0x25, 0x8f, 0x35, 0xfe, 0xff,
	0xff, 0xbe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x56, 0xf8, 0xa5, 0xb6, 0xc9, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FailedTransfers) > 0 {
		for iNdEx := len(m.FailedTransfers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FailedTransfers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	{
		size, err := m.TransferQueue.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.Chains) > 0 {
		for iNdEx := len(m.Chains) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Chains[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.CollectorAddress) > 0 {
		i -= len(m.CollectorAddress)
		copy(dAtA[i:], m.CollectorAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.CollectorAddress)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = len(m.CollectorAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.Chains) > 0 {
		for _, e := range m.Chains {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.TransferQueue.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.FailedTransfers) > 0 {
		for _, e := range m.FailedTransfers {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectorAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollectorAddress = append(m.CollectorAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.CollectorAddress == nil {
				m.CollectorAddress = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chains", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chains = append(m.Chains, CosmosChain{})
			if err := m.Chains[len(m.Chains)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferQueue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TransferQueue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FailedTransfers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FailedTransfers = append(m.FailedTransfers, IBCTransfer{})
			if err := m.FailedTransfers[len(m.FailedTransfers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
