// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nexus/v1beta1/types.proto

package types2

import (
	fmt "fmt"
	exported2 "github.com/axelarnetwork/axelar-core/x/nexus/exported2"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ChainState represents the state of a registered blockchain
type ChainState struct {
	Chain       exported2.Chain                                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain"`
	Maintainers []github_com_cosmos_cosmos_sdk_types.ValAddress `protobuf:"bytes,2,rep,name=maintainers,proto3,casttype=github.com/cosmos/cosmos-sdk/types.ValAddress" json:"maintainers,omitempty"`
	Activated   bool                                            `protobuf:"varint,3,opt,name=activated,proto3" json:"activated,omitempty"`
	Assets      []exported2.Asset                               `protobuf:"bytes,5,rep,name=assets,proto3" json:"assets"`
}

func (m *ChainState) Reset()         { *m = ChainState{} }
func (m *ChainState) String() string { return proto.CompactTextString(m) }
func (*ChainState) ProtoMessage()    {}
func (*ChainState) Descriptor() ([]byte, []int) {
	return fileDescriptor_1651b8508c88d62f, []int{0}
}
func (m *ChainState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainState.Merge(m, src)
}
func (m *ChainState) XXX_Size() int {
	return m.Size()
}
func (m *ChainState) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainState.DiscardUnknown(m)
}

var xxx_messageInfo_ChainState proto.InternalMessageInfo

type LinkedAddresses struct {
	DepositAddress   exported2.CrossChainAddress `protobuf:"bytes,1,opt,name=deposit_address,json=depositAddress,proto3" json:"deposit_address"`
	RecipientAddress exported2.CrossChainAddress `protobuf:"bytes,2,opt,name=recipient_address,json=recipientAddress,proto3" json:"recipient_address"`
}

func (m *LinkedAddresses) Reset()         { *m = LinkedAddresses{} }
func (m *LinkedAddresses) String() string { return proto.CompactTextString(m) }
func (*LinkedAddresses) ProtoMessage()    {}
func (*LinkedAddresses) Descriptor() ([]byte, []int) {
	return fileDescriptor_1651b8508c88d62f, []int{1}
}
func (m *LinkedAddresses) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LinkedAddresses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LinkedAddresses.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LinkedAddresses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkedAddresses.Merge(m, src)
}
func (m *LinkedAddresses) XXX_Size() int {
	return m.Size()
}
func (m *LinkedAddresses) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkedAddresses.DiscardUnknown(m)
}

var xxx_messageInfo_LinkedAddresses proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ChainState)(nil), "nexus.v1beta1.ChainState")
	proto.RegisterType((*LinkedAddresses)(nil), "nexus.v1beta1.LinkedAddresses")
}

func init() { proto.RegisterFile("nexus/v1beta1/types.proto", fileDescriptor_1651b8508c88d62f) }

var fileDescriptor_1651b8508c88d62f = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0xcf, 0xd2, 0x40,
	0x10, 0xc6, 0xbb, 0x2f, 0xf0, 0x06, 0x17, 0x15, 0x6c, 0x3c, 0x54, 0xa2, 0x4b, 0xc3, 0x09, 0x0f,
	0xb4, 0x01, 0x4e, 0xc6, 0x13, 0x78, 0x33, 0x5e, 0x84, 0xc4, 0x18, 0x63, 0x62, 0xb6, 0xed, 0x04,
	0x36, 0xc0, 0x6e, 0xb3, 0xb3, 0x60, 0xfd, 0x16, 0x7e, 0x2c, 0xbc, 0x71, 0xf4, 0x44, 0x14, 0xbe,
	0x85, 0x89, 0x89, 0xa1, 0x5d, 0xfe, 0x1c, 0xd4, 0xc3, 0x7b, 0x6a, 0xf7, 0x79, 0x76, 0x7e, 0xf3,
	0x64, 0x76, 0xe8, 0x13, 0x09, 0xd9, 0x0a, 0xc3, 0x75, 0x2f, 0x02, 0xc3, 0x7b, 0xa1, 0xf9, 0x92,
	0x02, 0x06, 0xa9, 0x56, 0x46, 0xb9, 0x0f, 0x72, 0x2b, 0xb0, 0x56, 0xf3, 0xf1, 0x54, 0x4d, 0x55,
	0xee, 0x84, 0xc7, 0xbf, 0xe2, 0x52, 0x93, 0xc5, 0x0a, 0x97, 0x0a, 0xc3, 0x88, 0x23, 0x9c, 0x29,
	0xb1, 0x12, 0xd2, 0xfa, 0xed, 0x82, 0x0f, 0x59, 0xaa, 0xb4, 0x81, 0xe4, 0x6f, 0x8d, 0xda, 0xbf,
	0x09, 0xa5, 0xaf, 0x66, 0x5c, 0xc8, 0x89, 0xe1, 0x06, 0xdc, 0x17, 0xb4, 0x12, 0x1f, 0x4f, 0x1e,
	0xf1, 0x49, 0xa7, 0xd6, 0x7f, 0x16, 0x14, 0x39, 0x4e, 0x88, 0x53, 0xa0, 0x20, 0x2f, 0x19, 0x95,
	0x37, 0xbb, 0x96, 0x33, 0x2e, 0x2a, 0xdc, 0x09, 0xad, 0x2d, 0xb9, 0x90, 0x86, 0x0b, 0x09, 0x1a,
	0xbd, 0x1b, 0xbf, 0xd4, 0xb9, 0x3f, 0xea, 0xfd, 0xda, 0xb5, 0xba, 0x53, 0x61, 0x66, 0xab, 0x28,
	0x88, 0xd5, 0x32, 0xb4, 0x89, 0x8b, 0x4f, 0x17, 0x93, 0xb9, 0x0d, 0xf3, 0x8e, 0x2f, 0x86, 0x49,
	0xa2, 0x01, 0x71, 0x7c, 0x4d, 0x71, 0x9f, 0xd2, 0x7b, 0x3c, 0x36, 0x62, 0xcd, 0x0d, 0x24, 0x5e,
	0xc9, 0x27, 0x9d, 0xea, 0xf8, 0x22, 0xb8, 0x2f, 0xe9, 0x2d, 0x47, 0x04, 0x83, 0x5e, 0xc5, 0x2f,
	0xfd, 0x2f, 0xee, 0xf0, 0x78, 0xcb, 0xc6, 0xb5, 0x25, 0xaf, 0xcb, 0xd5, 0x72, 0xa3, 0xd2, 0xfe,
	0x46, 0x68, 0xfd, 0x8d, 0x90, 0x73, 0x48, 0x6c, 0x7f, 0x40, 0xf7, 0x3d, 0xad, 0x27, 0x90, 0x2a,
	0x14, 0xe6, 0x13, 0x2f, 0x44, 0x3b, 0x8e, 0xe7, 0xff, 0x1c, 0x87, 0x56, 0x88, 0xf9, 0x4c, 0x2c,
	0xc5, 0xf6, 0x7a, 0x68, 0x39, 0x56, 0x75, 0x3f, 0xd2, 0x47, 0x1a, 0x62, 0x91, 0x0a, 0x90, 0x17,
	0xf6, 0xcd, 0xdd, 0xd8, 0x8d, 0x33, 0xe9, 0xa4, 0xbf, 0xdd, 0xfc, 0x64, 0xce, 0x66, 0xcf, 0xc8,
	0x76, 0xcf, 0xc8, 0x8f, 0x3d, 0x23, 0x5f, 0x0f, 0xcc, 0xd9, 0x1e, 0x98, 0xf3, 0xfd, 0xc0, 0x9c,
	0x0f, 0x83, 0xab, 0x67, 0xe0, 0x19, 0x2c, 0xb8, 0x96, 0x60, 0x3e, 0x2b, 0x3d, 0xb7, 0xa7, 0x6e,
	0xac, 0x34, 0x84, 0x59, 0x58, 0x2c, 0x4d, 0xfe, 0x2c, 0xfd, 0xe8, 0x36, 0xdf, 0x92, 0xc1, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x25, 0xbf, 0x37, 0xab, 0x02, 0x00, 0x00,
}

func (m *ChainState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Assets) > 0 {
		for iNdEx := len(m.Assets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Assets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.Activated {
		i--
		if m.Activated {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Maintainers) > 0 {
		for iNdEx := len(m.Maintainers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Maintainers[iNdEx])
			copy(dAtA[i:], m.Maintainers[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.Maintainers[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Chain.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *LinkedAddresses) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LinkedAddresses) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LinkedAddresses) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.RecipientAddress.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.DepositAddress.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ChainState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Chain.Size()
	n += 1 + l + sovTypes(uint64(l))
	if len(m.Maintainers) > 0 {
		for _, b := range m.Maintainers {
			l = len(b)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.Activated {
		n += 2
	}
	if len(m.Assets) > 0 {
		for _, e := range m.Assets {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *LinkedAddresses) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DepositAddress.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = m.RecipientAddress.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ChainState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Chain.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Maintainers", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Maintainers = append(m.Maintainers, make([]byte, postIndex-iNdEx))
			copy(m.Maintainers[len(m.Maintainers)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Activated", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Activated = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Assets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Assets = append(m.Assets, exported2.Asset{})
			if err := m.Assets[len(m.Assets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LinkedAddresses) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LinkedAddresses: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LinkedAddresses: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositAddress", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DepositAddress.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecipientAddress", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RecipientAddress.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
