// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tss/exported/v1beta1/types.proto

package exported

import (
	fmt "fmt"
	utils "github.com/axelarnetwork/axelar-core/utils"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type KeyRole int32

const (
	Unknown      KeyRole = 0
	MasterKey    KeyRole = 1
	SecondaryKey KeyRole = 2
	ExternalKey  KeyRole = 3
)

var KeyRole_name = map[int32]string{
	0: "KEY_ROLE_UNSPECIFIED",
	1: "KEY_ROLE_MASTER_KEY",
	2: "KEY_ROLE_SECONDARY_KEY",
	3: "KEY_ROLE_EXTERNAL_KEY",
}

var KeyRole_value = map[string]int32{
	"KEY_ROLE_UNSPECIFIED":   0,
	"KEY_ROLE_MASTER_KEY":    1,
	"KEY_ROLE_SECONDARY_KEY": 2,
	"KEY_ROLE_EXTERNAL_KEY":  3,
}

func (x KeyRole) String() string {
	return proto.EnumName(KeyRole_name, int32(x))
}

func (KeyRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6a3f02740fd114b9, []int{0}
}

type KeyShareDistributionPolicy int32

const (
	Unspecified     KeyShareDistributionPolicy = 0
	WeightedByStake KeyShareDistributionPolicy = 1
	OnePerValidator KeyShareDistributionPolicy = 2
)

var KeyShareDistributionPolicy_name = map[int32]string{
	0: "KEY_SHARE_DISTRIBUTION_POLICY_UNSPECIFIED",
	1: "KEY_SHARE_DISTRIBUTION_POLICY_WEIGHTED_BY_STAKE",
	2: "KEY_SHARE_DISTRIBUTION_POLICY_ONE_PER_VALIDATOR",
}

var KeyShareDistributionPolicy_value = map[string]int32{
	"KEY_SHARE_DISTRIBUTION_POLICY_UNSPECIFIED":       0,
	"KEY_SHARE_DISTRIBUTION_POLICY_WEIGHTED_BY_STAKE": 1,
	"KEY_SHARE_DISTRIBUTION_POLICY_ONE_PER_VALIDATOR": 2,
}

func (x KeyShareDistributionPolicy) String() string {
	return proto.EnumName(KeyShareDistributionPolicy_name, int32(x))
}

func (KeyShareDistributionPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6a3f02740fd114b9, []int{1}
}

type AckType int32

const (
	AckType_Unspecified AckType = 0
	AckType_Keygen      AckType = 1
	AckType_Sign        AckType = 2
)

var AckType_name = map[int32]string{
	0: "ACK_TYPE_UNSPECIFIED",
	1: "ACK_TYPE_KEYGEN",
	2: "ACK_TYPE_SIGN",
}

var AckType_value = map[string]int32{
	"ACK_TYPE_UNSPECIFIED": 0,
	"ACK_TYPE_KEYGEN":      1,
	"ACK_TYPE_SIGN":        2,
}

func (x AckType) String() string {
	return proto.EnumName(AckType_name, int32(x))
}

func (AckType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6a3f02740fd114b9, []int{2}
}

type SigStatus int32

const (
	SigStatus_Unspecified SigStatus = 0
	SigStatus_Scheduled   SigStatus = 1
	SigStatus_Signing     SigStatus = 2
	SigStatus_Signed      SigStatus = 3
	SigStatus_Aborted     SigStatus = 4
	SigStatus_Invalid     SigStatus = 5
)

var SigStatus_name = map[int32]string{
	0: "SIG_STATUS_UNSPECIFIED",
	1: "SIG_STATUS_SCHEDULED",
	2: "SIG_STATUS_SIGNING",
	3: "SIG_STATUS_SIGNED",
	4: "SIG_STATUS_ABORTED",
	5: "SIG_STATUS_INVALID",
}

var SigStatus_value = map[string]int32{
	"SIG_STATUS_UNSPECIFIED": 0,
	"SIG_STATUS_SCHEDULED":   1,
	"SIG_STATUS_SIGNING":     2,
	"SIG_STATUS_SIGNED":      3,
	"SIG_STATUS_ABORTED":     4,
	"SIG_STATUS_INVALID":     5,
}

func (x SigStatus) String() string {
	return proto.EnumName(SigStatus_name, int32(x))
}

func (SigStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6a3f02740fd114b9, []int{3}
}

// KeyRequirement defines requirements for keys
type KeyRequirement struct {
	KeyRole                    KeyRole                    `protobuf:"varint,1,opt,name=key_role,json=keyRole,proto3,enum=tss.exported.v1beta1.KeyRole" json:"key_role,omitempty"`
	MinKeygenThreshold         utils.Threshold            `protobuf:"bytes,2,opt,name=min_keygen_threshold,json=minKeygenThreshold,proto3" json:"min_keygen_threshold"`
	SafetyThreshold            utils.Threshold            `protobuf:"bytes,3,opt,name=safety_threshold,json=safetyThreshold,proto3" json:"safety_threshold"`
	KeyShareDistributionPolicy KeyShareDistributionPolicy `protobuf:"varint,4,opt,name=key_share_distribution_policy,json=keyShareDistributionPolicy,proto3,enum=tss.exported.v1beta1.KeyShareDistributionPolicy" json:"key_share_distribution_policy,omitempty"`
	MaxTotalShareCount         int64                      `protobuf:"varint,5,opt,name=max_total_share_count,json=maxTotalShareCount,proto3" json:"max_total_share_count,omitempty"`
	KeygenVotingThreshold      utils.Threshold            `protobuf:"bytes,6,opt,name=keygen_voting_threshold,json=keygenVotingThreshold,proto3" json:"keygen_voting_threshold"`
	SignVotingThreshold        utils.Threshold            `protobuf:"bytes,7,opt,name=sign_voting_threshold,json=signVotingThreshold,proto3" json:"sign_voting_threshold"`
	KeygenTimeout              int64                      `protobuf:"varint,8,opt,name=keygen_timeout,json=keygenTimeout,proto3" json:"keygen_timeout,omitempty"`
	SignTimeout                int64                      `protobuf:"varint,9,opt,name=sign_timeout,json=signTimeout,proto3" json:"sign_timeout,omitempty"`
}

func (m *KeyRequirement) Reset()         { *m = KeyRequirement{} }
func (m *KeyRequirement) String() string { return proto.CompactTextString(m) }
func (*KeyRequirement) ProtoMessage()    {}
func (*KeyRequirement) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a3f02740fd114b9, []int{0}
}
func (m *KeyRequirement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeyRequirement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeyRequirement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeyRequirement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyRequirement.Merge(m, src)
}
func (m *KeyRequirement) XXX_Size() int {
	return m.Size()
}
func (m *KeyRequirement) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyRequirement.DiscardUnknown(m)
}

var xxx_messageInfo_KeyRequirement proto.InternalMessageInfo

func (m *KeyRequirement) GetKeyRole() KeyRole {
	if m != nil {
		return m.KeyRole
	}
	return Unknown
}

func (m *KeyRequirement) GetMinKeygenThreshold() utils.Threshold {
	if m != nil {
		return m.MinKeygenThreshold
	}
	return utils.Threshold{}
}

func (m *KeyRequirement) GetSafetyThreshold() utils.Threshold {
	if m != nil {
		return m.SafetyThreshold
	}
	return utils.Threshold{}
}

func (m *KeyRequirement) GetKeyShareDistributionPolicy() KeyShareDistributionPolicy {
	if m != nil {
		return m.KeyShareDistributionPolicy
	}
	return Unspecified
}

func (m *KeyRequirement) GetMaxTotalShareCount() int64 {
	if m != nil {
		return m.MaxTotalShareCount
	}
	return 0
}

func (m *KeyRequirement) GetKeygenVotingThreshold() utils.Threshold {
	if m != nil {
		return m.KeygenVotingThreshold
	}
	return utils.Threshold{}
}

func (m *KeyRequirement) GetSignVotingThreshold() utils.Threshold {
	if m != nil {
		return m.SignVotingThreshold
	}
	return utils.Threshold{}
}

func (m *KeyRequirement) GetKeygenTimeout() int64 {
	if m != nil {
		return m.KeygenTimeout
	}
	return 0
}

func (m *KeyRequirement) GetSignTimeout() int64 {
	if m != nil {
		return m.SignTimeout
	}
	return 0
}

// SignInfo holds information about a sign request
type SignInfo struct {
	KeyID           string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	SigID           string `protobuf:"bytes,2,opt,name=sig_id,json=sigId,proto3" json:"sig_id,omitempty"`
	Msg             []byte `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	SnapshotCounter int64  `protobuf:"varint,4,opt,name=snapshot_counter,json=snapshotCounter,proto3" json:"snapshot_counter,omitempty"`
	RequestModule   string `protobuf:"bytes,5,opt,name=request_module,json=requestModule,proto3" json:"request_module,omitempty"`
	Metadata        string `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *SignInfo) Reset()         { *m = SignInfo{} }
func (m *SignInfo) String() string { return proto.CompactTextString(m) }
func (*SignInfo) ProtoMessage()    {}
func (*SignInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a3f02740fd114b9, []int{1}
}
func (m *SignInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SignInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SignInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SignInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInfo.Merge(m, src)
}
func (m *SignInfo) XXX_Size() int {
	return m.Size()
}
func (m *SignInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SignInfo proto.InternalMessageInfo

func (m *SignInfo) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *SignInfo) GetSigID() string {
	if m != nil {
		return m.SigID
	}
	return ""
}

func (m *SignInfo) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *SignInfo) GetSnapshotCounter() int64 {
	if m != nil {
		return m.SnapshotCounter
	}
	return 0
}

func (m *SignInfo) GetRequestModule() string {
	if m != nil {
		return m.RequestModule
	}
	return ""
}

func (m *SignInfo) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func init() {
	proto.RegisterEnum("tss.exported.v1beta1.KeyRole", KeyRole_name, KeyRole_value)
	proto.RegisterEnum("tss.exported.v1beta1.KeyShareDistributionPolicy", KeyShareDistributionPolicy_name, KeyShareDistributionPolicy_value)
	proto.RegisterEnum("tss.exported.v1beta1.AckType", AckType_name, AckType_value)
	proto.RegisterEnum("tss.exported.v1beta1.SigStatus", SigStatus_name, SigStatus_value)
	proto.RegisterType((*KeyRequirement)(nil), "tss.exported.v1beta1.KeyRequirement")
	proto.RegisterType((*SignInfo)(nil), "tss.exported.v1beta1.SignInfo")
}

func init() { proto.RegisterFile("tss/exported/v1beta1/types.proto", fileDescriptor_6a3f02740fd114b9) }

var fileDescriptor_6a3f02740fd114b9 = []byte{
	// 1013 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x95, 0x4f, 0x6f, 0xe2, 0xc6,
	0x1b, 0xc7, 0x31, 0xe4, 0x0f, 0x4c, 0x36, 0x1b, 0xff, 0x26, 0x64, 0x7f, 0xc8, 0x55, 0x88, 0x77,
	0xab, 0x6d, 0x93, 0xb4, 0x85, 0x66, 0xf7, 0xd2, 0x53, 0x25, 0xc0, 0x53, 0x62, 0x91, 0x00, 0xb2,
	0x4d, 0xb6, 0xf4, 0x62, 0x39, 0x78, 0x62, 0x46, 0x80, 0x87, 0xb5, 0x87, 0x2c, 0x96, 0x7a, 0xad,
	0x54, 0x71, 0xea, 0x1b, 0xe0, 0xd4, 0x1e, 0xfa, 0x22, 0xfa, 0x02, 0xf6, 0x54, 0xed, 0xb1, 0xa7,
	0x55, 0x95, 0xbc, 0x8b, 0x4a, 0x95, 0xaa, 0x19, 0x03, 0x41, 0xe9, 0xa6, 0xc9, 0x6d, 0x78, 0xe6,
	0xf3, 0xfd, 0xce, 0x7c, 0xfd, 0x3c, 0xd8, 0x40, 0x65, 0x61, 0x58, 0xc4, 0xe3, 0x21, 0x0d, 0x18,
	0x76, 0x8b, 0x97, 0x47, 0xe7, 0x98, 0x39, 0x47, 0x45, 0x16, 0x0d, 0x71, 0x58, 0x18, 0x06, 0x94,
	0x51, 0x98, 0x65, 0x61, 0x58, 0x98, 0x13, 0x85, 0x19, 0xa1, 0xec, 0x8e, 0x18, 0xe9, 0x87, 0x37,
	0x82, 0x6e, 0x80, 0xc3, 0x2e, 0xed, 0xbb, 0xb1, 0x48, 0xc9, 0x7a, 0xd4, 0xa3, 0x62, 0x59, 0xe4,
	0xab, 0xb8, 0xfa, 0xec, 0x87, 0x55, 0xf0, 0xb8, 0x86, 0x23, 0x03, 0xbf, 0x1e, 0x91, 0x00, 0x0f,
	0xb0, 0xcf, 0xe0, 0x57, 0x20, 0xdd, 0xc3, 0x91, 0x1d, 0xd0, 0x3e, 0xce, 0x49, 0xaa, 0xb4, 0xff,
	0xf8, 0xc5, 0x6e, 0xe1, 0x43, 0x07, 0x16, 0xb8, 0x8e, 0xf6, 0xb1, 0xb1, 0xde, 0x8b, 0x17, 0xb0,
	0x09, 0xb2, 0x03, 0xe2, 0xdb, 0x3d, 0x1c, 0x79, 0xd8, 0xb7, 0x17, 0x17, 0xc8, 0x25, 0x55, 0x69,
	0x7f, 0xe3, 0x45, 0xae, 0x20, 0x2e, 0xb8, 0x90, 0x5b, 0xf3, 0xfd, 0xf2, 0xca, 0xdb, 0xf7, 0x7b,
	0x09, 0x03, 0x0e, 0x88, 0x5f, 0x13, 0xd2, 0xc5, 0x0e, 0xd4, 0x81, 0x1c, 0x3a, 0x17, 0x98, 0x45,
	0x4b, 0x6e, 0xa9, 0x07, 0xb9, 0x6d, 0xc5, 0xba, 0x1b, 0xab, 0x10, 0xec, 0xf2, 0x58, 0x61, 0xd7,
	0x09, 0xb0, 0xed, 0x92, 0x90, 0x05, 0xe4, 0x7c, 0xc4, 0x08, 0xf5, 0xed, 0x21, 0xed, 0x93, 0x4e,
	0x94, 0x5b, 0x11, 0x59, 0xbf, 0xbc, 0x33, 0xab, 0xc9, 0x95, 0xda, 0x92, 0xb0, 0x29, 0x74, 0x86,
	0xd2, 0xbb, 0x73, 0x0f, 0x1e, 0x81, 0x9d, 0x81, 0x33, 0xb6, 0x19, 0x65, 0x4e, 0x7f, 0x76, 0x74,
	0x87, 0x8e, 0x7c, 0x96, 0x5b, 0x55, 0xa5, 0xfd, 0x94, 0x01, 0x07, 0xce, 0xd8, 0xe2, 0x7b, 0x42,
	0x5f, 0xe1, 0x3b, 0xf0, 0x0c, 0xfc, 0x7f, 0xf6, 0x00, 0x2f, 0x29, 0x23, 0xbe, 0xb7, 0x94, 0x7c,
	0xed, 0x41, 0xc9, 0x77, 0x62, 0xf9, 0x99, 0x50, 0xdf, 0xe4, 0x37, 0xc0, 0x4e, 0x48, 0xbc, 0x0f,
	0xb8, 0xae, 0x3f, 0xc8, 0x75, 0x9b, 0x8b, 0x6f, 0x7b, 0x3e, 0x07, 0x8f, 0xe7, 0xcd, 0x26, 0x03,
	0x4c, 0x47, 0x2c, 0x97, 0x16, 0xb9, 0x36, 0xe3, 0xaa, 0x15, 0x17, 0xe1, 0x53, 0xf0, 0x48, 0x1c,
	0x3d, 0x87, 0x32, 0x02, 0xda, 0xe0, 0xb5, 0x19, 0xf2, 0xec, 0x77, 0x09, 0xa4, 0x4d, 0xe2, 0xf9,
	0xba, 0x7f, 0x41, 0xa1, 0x0a, 0xd6, 0x78, 0xab, 0x88, 0x2b, 0xe6, 0x2f, 0x53, 0xce, 0x5c, 0xbd,
	0xdf, 0x5b, 0xad, 0xe1, 0x48, 0xd7, 0x8c, 0xd5, 0x1e, 0x8e, 0x74, 0x97, 0x13, 0x21, 0xf1, 0x38,
	0x91, 0xbc, 0x21, 0x4c, 0xe2, 0x71, 0x22, 0x24, 0x9e, 0xee, 0x42, 0x19, 0xa4, 0x06, 0xa1, 0x27,
	0x86, 0xe5, 0x91, 0xc1, 0x97, 0xf0, 0x00, 0xc8, 0xa1, 0xef, 0x0c, 0xc3, 0x2e, 0x65, 0x71, 0x13,
	0x70, 0x20, 0x7a, 0x9e, 0x32, 0xb6, 0xe6, 0xf5, 0x4a, 0x5c, 0xe6, 0xb9, 0x02, 0xfc, 0x7a, 0x84,
	0x43, 0x66, 0x0f, 0xa8, 0x3b, 0xea, 0x63, 0xd1, 0xaf, 0x8c, 0xb1, 0x39, 0xab, 0x9e, 0x8a, 0x22,
	0x54, 0x40, 0x7a, 0x80, 0x99, 0xe3, 0x3a, 0xcc, 0x11, 0xbd, 0xc9, 0x18, 0x8b, 0xdf, 0x87, 0xbf,
	0x49, 0x60, 0x7d, 0xf6, 0x07, 0x81, 0xcf, 0x41, 0xb6, 0x86, 0xda, 0xb6, 0xd1, 0x38, 0x41, 0x76,
	0xab, 0x6e, 0x36, 0x51, 0x45, 0xff, 0x46, 0x47, 0x9a, 0x9c, 0x50, 0x36, 0x26, 0x53, 0x75, 0xbd,
	0xe5, 0xf7, 0x7c, 0xfa, 0xc6, 0x87, 0x9f, 0x80, 0xed, 0x05, 0x76, 0x5a, 0x32, 0x2d, 0x64, 0xd8,
	0x35, 0xd4, 0x96, 0x25, 0x65, 0x73, 0x32, 0x55, 0x33, 0xa7, 0x4e, 0xc8, 0x70, 0x50, 0xc3, 0x11,
	0xfc, 0x1c, 0x3c, 0x59, 0x70, 0x26, 0xaa, 0x34, 0xea, 0x5a, 0xc9, 0x68, 0x0b, 0x34, 0xa9, 0xc8,
	0x93, 0xa9, 0xfa, 0xc8, 0xc4, 0x1d, 0xea, 0xbb, 0x4e, 0x10, 0x71, 0xfa, 0x10, 0xec, 0x2c, 0x68,
	0xf4, 0xad, 0x85, 0x8c, 0x7a, 0xe9, 0x44, 0xc0, 0x29, 0x65, 0x6b, 0x32, 0x55, 0x37, 0xd0, 0x98,
	0xe1, 0xc0, 0x77, 0xfa, 0x35, 0x1c, 0x29, 0xe9, 0x1f, 0x7f, 0xce, 0x27, 0x7e, 0xfd, 0x25, 0x2f,
	0x1d, 0xfe, 0x25, 0x01, 0xe5, 0xee, 0x99, 0x87, 0x5f, 0x83, 0x03, 0x6e, 0x6a, 0x1e, 0x97, 0x0c,
	0x64, 0x6b, 0xba, 0x69, 0x19, 0x7a, 0xb9, 0x65, 0xe9, 0x8d, 0xba, 0xdd, 0x6c, 0x9c, 0xe8, 0x95,
	0xf6, 0xad, 0x98, 0xe2, 0xa0, 0x96, 0x1f, 0x0e, 0x71, 0x87, 0x5c, 0x10, 0xec, 0xc2, 0x63, 0x50,
	0xfc, 0x6f, 0xfd, 0x2b, 0xa4, 0x57, 0x8f, 0x2d, 0xa4, 0xd9, 0xe5, 0xb6, 0x6d, 0x5a, 0xa5, 0x1a,
	0x92, 0x25, 0x65, 0x7b, 0x32, 0x55, 0xb7, 0x5e, 0x61, 0xe2, 0x75, 0x19, 0x76, 0xcb, 0x91, 0xc9,
	0x9c, 0x1e, 0xbe, 0xdf, 0xa9, 0x51, 0x47, 0x76, 0x13, 0x19, 0xf6, 0x59, 0xe9, 0x44, 0xd7, 0x4a,
	0x56, 0xc3, 0x90, 0x93, 0xb1, 0x53, 0xc3, 0xc7, 0x4d, 0x1c, 0x9c, 0x39, 0x7d, 0xe2, 0x3a, 0x8c,
	0x06, 0x4b, 0xe1, 0xbf, 0x07, 0xeb, 0xa5, 0x4e, 0xcf, 0x8a, 0x86, 0x18, 0x1e, 0x80, 0x6c, 0xa9,
	0x52, 0xb3, 0xad, 0x76, 0x13, 0xdd, 0x97, 0x69, 0x0f, 0x6c, 0x2d, 0xd0, 0x1a, 0x6a, 0x57, 0x51,
	0x5d, 0x96, 0x14, 0x30, 0x99, 0xaa, 0x6b, 0xf1, 0x5b, 0x0d, 0x7e, 0x04, 0x36, 0x17, 0x80, 0xa9,
	0x57, 0xeb, 0x72, 0x52, 0x49, 0x4f, 0xa6, 0xea, 0x0a, 0x9f, 0x7b, 0x71, 0xba, 0x24, 0x4e, 0xff,
	0x5b, 0x02, 0x19, 0x93, 0x78, 0x26, 0x73, 0xd8, 0x28, 0x84, 0x9f, 0x81, 0x27, 0xa6, 0x5e, 0xe5,
	0xcf, 0xc0, 0x6a, 0x99, 0xf7, 0x5d, 0xe1, 0x53, 0x90, 0x5d, 0x82, 0xcd, 0xca, 0x31, 0xd2, 0x5a,
	0x27, 0x48, 0x9b, 0x8f, 0x90, 0xd9, 0xe9, 0x62, 0x3e, 0xb8, 0x2e, 0xfc, 0x18, 0xc0, 0x65, 0x50,
	0xaf, 0xd6, 0xf5, 0x7a, 0x55, 0x4e, 0xc6, 0xf3, 0xc8, 0xef, 0x43, 0x7c, 0x0f, 0x3e, 0x05, 0xff,
	0xbb, 0x05, 0x21, 0x4d, 0x4e, 0xc5, 0x91, 0x38, 0xf3, 0x2f, 0x9f, 0x52, 0xb9, 0x61, 0x58, 0x48,
	0x93, 0x57, 0x62, 0x9f, 0xd2, 0xb9, 0x78, 0x87, 0xde, 0x82, 0xf4, 0xba, 0xe8, 0x84, 0xbc, 0x1a,
	0x43, 0xba, 0x7f, 0xc9, 0x3b, 0x70, 0x93, 0xbf, 0x7c, 0xfa, 0xf6, 0x2a, 0x2f, 0xbd, 0xbb, 0xca,
	0x4b, 0x7f, 0x5e, 0xe5, 0xa5, 0x9f, 0xae, 0xf3, 0x89, 0x77, 0xd7, 0xf9, 0xc4, 0x1f, 0xd7, 0xf9,
	0xc4, 0x77, 0x2f, 0x3d, 0xc2, 0xba, 0xa3, 0xf3, 0x42, 0x87, 0x0e, 0x8a, 0xce, 0x18, 0xf7, 0x9d,
	0xc0, 0xc7, 0xec, 0x0d, 0x0d, 0x7a, 0xb3, 0x5f, 0x5f, 0x74, 0x68, 0x80, 0x8b, 0xe3, 0xe2, 0xf2,
	0x07, 0xf4, 0x7c, 0x4d, 0x7c, 0xe8, 0x5e, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x2a, 0xcf,
	0x75, 0x57, 0x07, 0x00, 0x00,
}

func (m *KeyRequirement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyRequirement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyRequirement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SignTimeout != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SignTimeout))
		i--
		dAtA[i] = 0x48
	}
	if m.KeygenTimeout != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.KeygenTimeout))
		i--
		dAtA[i] = 0x40
	}
	{
		size, err := m.SignVotingThreshold.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.KeygenVotingThreshold.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.MaxTotalShareCount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxTotalShareCount))
		i--
		dAtA[i] = 0x28
	}
	if m.KeyShareDistributionPolicy != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.KeyShareDistributionPolicy))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.SafetyThreshold.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.MinKeygenThreshold.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.KeyRole != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.KeyRole))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SignInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SignInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SignInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metadata) > 0 {
		i -= len(m.Metadata)
		copy(dAtA[i:], m.Metadata)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Metadata)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.RequestModule) > 0 {
		i -= len(m.RequestModule)
		copy(dAtA[i:], m.RequestModule)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RequestModule)))
		i--
		dAtA[i] = 0x2a
	}
	if m.SnapshotCounter != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SnapshotCounter))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Msg) > 0 {
		i -= len(m.Msg)
		copy(dAtA[i:], m.Msg)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Msg)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SigID) > 0 {
		i -= len(m.SigID)
		copy(dAtA[i:], m.SigID)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SigID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.KeyID) > 0 {
		i -= len(m.KeyID)
		copy(dAtA[i:], m.KeyID)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.KeyID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *KeyRequirement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.KeyRole != 0 {
		n += 1 + sovTypes(uint64(m.KeyRole))
	}
	l = m.MinKeygenThreshold.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = m.SafetyThreshold.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.KeyShareDistributionPolicy != 0 {
		n += 1 + sovTypes(uint64(m.KeyShareDistributionPolicy))
	}
	if m.MaxTotalShareCount != 0 {
		n += 1 + sovTypes(uint64(m.MaxTotalShareCount))
	}
	l = m.KeygenVotingThreshold.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = m.SignVotingThreshold.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.KeygenTimeout != 0 {
		n += 1 + sovTypes(uint64(m.KeygenTimeout))
	}
	if m.SignTimeout != 0 {
		n += 1 + sovTypes(uint64(m.SignTimeout))
	}
	return n
}

func (m *SignInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.KeyID)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.SigID)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.SnapshotCounter != 0 {
		n += 1 + sovTypes(uint64(m.SnapshotCounter))
	}
	l = len(m.RequestModule)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Metadata)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *KeyRequirement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeyRequirement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeyRequirement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyRole", wireType)
			}
			m.KeyRole = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyRole |= KeyRole(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinKeygenThreshold", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinKeygenThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SafetyThreshold", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SafetyThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyShareDistributionPolicy", wireType)
			}
			m.KeyShareDistributionPolicy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyShareDistributionPolicy |= KeyShareDistributionPolicy(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTotalShareCount", wireType)
			}
			m.MaxTotalShareCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTotalShareCount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeygenVotingThreshold", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.KeygenVotingThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignVotingThreshold", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SignVotingThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeygenTimeout", wireType)
			}
			m.KeygenTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeygenTimeout |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignTimeout", wireType)
			}
			m.SignTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignTimeout |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SignInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SignInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SignInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SigID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = append(m.Msg[:0], dAtA[iNdEx:postIndex]...)
			if m.Msg == nil {
				m.Msg = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SnapshotCounter", wireType)
			}
			m.SnapshotCounter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SnapshotCounter |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestModule", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestModule = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metadata = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
