// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: axelar/vote/exported/v1beta1/types.proto

package exported

import (
	fmt "fmt"
	utils "github.com/axelarnetwork/axelar-core/utils"
	exported "github.com/axelarnetwork/axelar-core/x/snapshot/exported"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PollState int32

const (
	NonExistent PollState = 0
	Pending     PollState = 1
	Completed   PollState = 2
	Failed      PollState = 3
)

var PollState_name = map[int32]string{
	0: "POLL_STATE_UNSPECIFIED",
	1: "POLL_STATE_PENDING",
	2: "POLL_STATE_COMPLETED",
	3: "POLL_STATE_FAILED",
}

var PollState_value = map[string]int32{
	"POLL_STATE_UNSPECIFIED": 0,
	"POLL_STATE_PENDING":     1,
	"POLL_STATE_COMPLETED":   2,
	"POLL_STATE_FAILED":      3,
}

func (x PollState) String() string {
	return proto.EnumName(PollState_name, int32(x))
}

func (PollState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9e15e2bdf7e02581, []int{0}
}

// PollMetadata represents a poll with write-in voting, i.e. the result of the
// vote can have any data type
type PollMetadata struct {
	ExpiresAt       int64             `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Result          *types.Any        `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	VotingThreshold utils.Threshold   `protobuf:"bytes,5,opt,name=voting_threshold,json=votingThreshold,proto3" json:"voting_threshold"`
	State           PollState         `protobuf:"varint,6,opt,name=state,proto3,enum=axelar.vote.exported.v1beta1.PollState" json:"state,omitempty"`
	MinVoterCount   int64             `protobuf:"varint,7,opt,name=min_voter_count,json=minVoterCount,proto3" json:"min_voter_count,omitempty"`
	RewardPoolName  string            `protobuf:"bytes,10,opt,name=reward_pool_name,json=rewardPoolName,proto3" json:"reward_pool_name,omitempty"`
	GracePeriod     int64             `protobuf:"varint,11,opt,name=grace_period,json=gracePeriod,proto3" json:"grace_period,omitempty"`
	CompletedAt     int64             `protobuf:"varint,12,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	ID              PollID            `protobuf:"varint,13,opt,name=id,proto3,customtype=PollID" json:"id"`
	Snapshot        exported.Snapshot `protobuf:"bytes,15,opt,name=snapshot,proto3" json:"snapshot"`
	Module          string            `protobuf:"bytes,16,opt,name=module,proto3" json:"module,omitempty"`
	ModuleMetadata  *types.Any        `protobuf:"bytes,17,opt,name=module_metadata,json=moduleMetadata,proto3" json:"module_metadata,omitempty"`
}

func (m *PollMetadata) Reset()         { *m = PollMetadata{} }
func (m *PollMetadata) String() string { return proto.CompactTextString(m) }
func (*PollMetadata) ProtoMessage()    {}
func (*PollMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e15e2bdf7e02581, []int{0}
}
func (m *PollMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PollMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PollMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PollMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollMetadata.Merge(m, src)
}
func (m *PollMetadata) XXX_Size() int {
	return m.Size()
}
func (m *PollMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_PollMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_PollMetadata proto.InternalMessageInfo

// PollKey represents the key data for a poll
//
// Deprecated: Do not use.
type PollKey struct {
	Module string `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	ID     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *PollKey) Reset()      { *m = PollKey{} }
func (*PollKey) ProtoMessage() {}
func (*PollKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e15e2bdf7e02581, []int{1}
}
func (m *PollKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PollKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PollKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PollKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollKey.Merge(m, src)
}
func (m *PollKey) XXX_Size() int {
	return m.Size()
}
func (m *PollKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PollKey.DiscardUnknown(m)
}

var xxx_messageInfo_PollKey proto.InternalMessageInfo

// Vote represents a vote result - kept for backward compatibility
//
// Deprecated: Do not use.
type Vote struct {
	// DEPRECATED: Removed in v0.18, reinstated in v1.3 for backward
	// compatibility. This field must remain to allow decoding of historical
	// transactions. DO NOT use in new code.
	ResultsDeprecated []*types.Any `protobuf:"bytes,1,rep,name=results_deprecated,json=resultsDeprecated,proto3" json:"results_deprecated,omitempty"` // Deprecated: Do not use.
	Result            *types.Any   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e15e2bdf7e02581, []int{2}
}
func (m *Vote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return m.Size()
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

// PollParticipants should be embedded in poll events in other modules
type PollParticipants struct {
	PollID       PollID                                          `protobuf:"varint,1,opt,name=poll_id,json=pollId,proto3,customtype=PollID" json:"poll_id"`
	Participants []github_com_cosmos_cosmos_sdk_types.ValAddress `protobuf:"bytes,2,rep,name=participants,proto3,casttype=github.com/cosmos/cosmos-sdk/types.ValAddress" json:"participants,omitempty"`
}

func (m *PollParticipants) Reset()         { *m = PollParticipants{} }
func (m *PollParticipants) String() string { return proto.CompactTextString(m) }
func (*PollParticipants) ProtoMessage()    {}
func (*PollParticipants) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e15e2bdf7e02581, []int{3}
}
func (m *PollParticipants) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PollParticipants) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PollParticipants.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PollParticipants) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollParticipants.Merge(m, src)
}
func (m *PollParticipants) XXX_Size() int {
	return m.Size()
}
func (m *PollParticipants) XXX_DiscardUnknown() {
	xxx_messageInfo_PollParticipants.DiscardUnknown(m)
}

var xxx_messageInfo_PollParticipants proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("axelar.vote.exported.v1beta1.PollState", PollState_name, PollState_value)
	proto.RegisterType((*PollMetadata)(nil), "axelar.vote.exported.v1beta1.PollMetadata")
	proto.RegisterType((*PollKey)(nil), "axelar.vote.exported.v1beta1.PollKey")
	proto.RegisterType((*Vote)(nil), "axelar.vote.exported.v1beta1.Vote")
	proto.RegisterType((*PollParticipants)(nil), "axelar.vote.exported.v1beta1.PollParticipants")
}

func init() {
	proto.RegisterFile("axelar/vote/exported/v1beta1/types.proto", fileDescriptor_9e15e2bdf7e02581)
}

var fileDescriptor_9e15e2bdf7e02581 = []byte{
	// 895 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xbf, 0x6f, 0xdb, 0xc6,
	0x17, 0xd7, 0x51, 0xb2, 0x2c, 0x9d, 0x64, 0x8b, 0x3e, 0x18, 0x06, 0xbf, 0xc2, 0xb7, 0x12, 0xe3,
	0x06, 0x89, 0xe0, 0xc6, 0x24, 0x9c, 0x76, 0x0a, 0xd0, 0x41, 0xb2, 0xe4, 0x40, 0xae, 0xac, 0x10,
	0xb4, 0x13, 0x14, 0x5d, 0x88, 0x33, 0xef, 0x2a, 0x11, 0x21, 0x79, 0xc4, 0xf1, 0xe4, 0xc8, 0x63,
	0xb7, 0xc2, 0x53, 0xc7, 0x0e, 0x35, 0x50, 0xa0, 0x1d, 0xba, 0xb7, 0x7b, 0x57, 0xa3, 0x53, 0xc6,
	0xa2, 0x83, 0xd1, 0xda, 0xff, 0x45, 0xa7, 0xe2, 0xf8, 0x43, 0x91, 0x91, 0x26, 0x53, 0x27, 0xdd,
	0xfb, 0xdc, 0xe7, 0x3d, 0xbd, 0xcf, 0xe7, 0xbd, 0x93, 0x60, 0x07, 0xcf, 0xa9, 0x8f, 0xb9, 0x79,
	0xc6, 0x04, 0x35, 0xe9, 0x3c, 0x62, 0x5c, 0x50, 0x62, 0x9e, 0xed, 0x9d, 0x52, 0x81, 0xf7, 0x4c,
	0x71, 0x1e, 0xd1, 0xd8, 0x88, 0x38, 0x13, 0x0c, 0xfd, 0x3f, 0x65, 0x1a, 0x92, 0x69, 0xe4, 0x4c,
	0x23, 0x63, 0x36, 0x37, 0x27, 0x6c, 0xc2, 0x12, 0xa2, 0x29, 0x4f, 0x69, 0x4e, 0xf3, 0x7f, 0x13,
	0xc6, 0x26, 0x3e, 0x35, 0x93, 0xe8, 0x74, 0xf6, 0xa5, 0x89, 0xc3, 0xf3, 0xfc, 0xca, 0x65, 0x71,
	0xc0, 0x62, 0x27, 0xcd, 0x49, 0x83, 0xec, 0xea, 0x51, 0xd6, 0x53, 0x1c, 0xe2, 0x28, 0x9e, 0x32,
	0xf1, 0xde, 0xbe, 0x9a, 0xf7, 0x33, 0xf6, 0x4c, 0x78, 0x7e, 0xfc, 0x86, 0x31, 0xe5, 0x34, 0x9e,
	0x32, 0x9f, 0xa4, 0xac, 0xed, 0x5f, 0x57, 0x60, 0xdd, 0x62, 0xbe, 0x7f, 0x44, 0x05, 0x26, 0x58,
	0x60, 0xf4, 0x01, 0x84, 0x74, 0x1e, 0x79, 0x9c, 0xc6, 0x0e, 0x16, 0x5a, 0x51, 0x07, 0x9d, 0xa2,
	0x5d, 0xcd, 0x90, 0xae, 0x40, 0x9f, 0xc3, 0x32, 0xa7, 0xf1, 0xcc, 0x17, 0x5a, 0x49, 0x07, 0x9d,
	0xda, 0xe3, 0x4d, 0x23, 0x95, 0x62, 0xe4, 0x52, 0x8c, 0x6e, 0x78, 0xde, 0xdb, 0xf9, 0xed, 0x97,
	0xdd, 0x07, 0x13, 0x4f, 0x4c, 0x67, 0xa7, 0x86, 0xcb, 0x82, 0x4c, 0x86, 0xe9, 0x32, 0x42, 0x5d,
	0xd3, 0x92, 0xcc, 0x23, 0xcc, 0xe3, 0x29, 0xf6, 0x29, 0xb7, 0xb3, 0x7a, 0xc8, 0x82, 0xea, 0x19,
	0x13, 0x5e, 0x38, 0x71, 0x16, 0x3d, 0x6a, 0x2b, 0xc9, 0x77, 0xb4, 0x8d, 0xcc, 0xe2, 0x44, 0x4a,
	0x6e, 0xad, 0x71, 0x92, 0xd3, 0x7a, 0xa5, 0xab, 0xeb, 0x76, 0xc1, 0x6e, 0xa4, 0xe9, 0x0b, 0x18,
	0x7d, 0x0a, 0x57, 0x62, 0x81, 0x05, 0xd5, 0xca, 0x3a, 0xe8, 0xac, 0x3f, 0x7e, 0x68, 0xbc, 0x6f,
	0x52, 0x86, 0x74, 0xe1, 0x58, 0xd2, 0xed, 0x34, 0x0b, 0x3d, 0x80, 0x8d, 0xc0, 0x0b, 0x1d, 0xc9,
	0xe6, 0x8e, 0xcb, 0x66, 0xa1, 0xd0, 0x56, 0x13, 0x3b, 0xd6, 0x02, 0x2f, 0x7c, 0x21, 0xd1, 0x7d,
	0x09, 0xa2, 0x0e, 0x54, 0x39, 0x7d, 0x85, 0x39, 0x71, 0x22, 0xc6, 0x7c, 0x27, 0xc4, 0x01, 0xd5,
	0xa0, 0x0e, 0x3a, 0x55, 0x7b, 0x3d, 0xc5, 0x2d, 0xc6, 0xfc, 0x31, 0x0e, 0x28, 0xba, 0x07, 0xeb,
	0x13, 0x8e, 0x5d, 0xea, 0x44, 0x94, 0x7b, 0x8c, 0x68, 0xb5, 0xa4, 0x5c, 0x2d, 0xc1, 0xac, 0x04,
	0x92, 0x14, 0x97, 0x05, 0x91, 0x4f, 0x05, 0x25, 0x72, 0x00, 0xf5, 0x94, 0xb2, 0xc0, 0xba, 0x02,
	0xdd, 0x87, 0x8a, 0x47, 0xb4, 0x35, 0x1d, 0x74, 0x4a, 0xbd, 0x4d, 0xa9, 0xfc, 0x8f, 0xeb, 0x76,
	0x59, 0x76, 0x3f, 0xec, 0xdf, 0x5c, 0xb7, 0x95, 0x61, 0xdf, 0x56, 0x3c, 0x82, 0x46, 0xb0, 0x92,
	0xef, 0x89, 0xd6, 0x48, 0x6c, 0xdc, 0xc9, 0xf5, 0xe7, 0xf8, 0xdb, 0x1e, 0x1c, 0x67, 0x37, 0x99,
	0xa3, 0x8b, 0x0a, 0x68, 0x0b, 0x96, 0x03, 0x46, 0x66, 0x3e, 0xd5, 0xd4, 0x44, 0x59, 0x16, 0x21,
	0x0f, 0x36, 0xd2, 0x93, 0x13, 0x64, 0x0b, 0xa4, 0x6d, 0xfc, 0x47, 0x7b, 0xb1, 0x9e, 0x16, 0xce,
	0x17, 0xf3, 0xb0, 0x54, 0x01, 0xaa, 0x72, 0x58, 0xaa, 0x54, 0xd4, 0xea, 0x61, 0xa9, 0x52, 0x55,
	0xe1, 0x61, 0xa9, 0xb2, 0xae, 0x36, 0xb6, 0xbb, 0x70, 0x55, 0x8a, 0xff, 0x8c, 0x9e, 0x2f, 0x75,
	0x09, 0xee, 0x74, 0xb9, 0x95, 0x38, 0xa6, 0x48, 0xac, 0x57, 0x7e, 0xe3, 0xd1, 0x93, 0xf2, 0xb7,
	0xdf, 0xb7, 0x0b, 0x1a, 0xd8, 0xfe, 0x0a, 0xc0, 0x92, 0x1c, 0x28, 0x7a, 0x0a, 0x51, 0xba, 0x8d,
	0xb1, 0x43, 0x68, 0xc4, 0xa9, 0x8b, 0x05, 0x25, 0x1a, 0xd0, 0x8b, 0xef, 0x54, 0xa4, 0x68, 0xc0,
	0xde, 0xc8, 0x72, 0xfa, 0x8b, 0x14, 0xf4, 0x68, 0xf1, 0x4c, 0x94, 0x77, 0xdb, 0x91, 0xaf, 0xfe,
	0x13, 0x45, 0x03, 0xdb, 0xdf, 0x01, 0xa8, 0x4a, 0x1d, 0x16, 0xe6, 0xc2, 0x73, 0xbd, 0x08, 0x87,
	0x22, 0x46, 0x7b, 0x70, 0x35, 0x62, 0xbe, 0xef, 0x78, 0x24, 0x51, 0x54, 0xea, 0x69, 0x6f, 0xcd,
	0x3b, 0x3b, 0xd9, 0x65, 0x49, 0x1c, 0x12, 0xf4, 0x1c, 0xd6, 0xa3, 0xa5, 0x12, 0x9a, 0xa2, 0x17,
	0x3b, 0xf5, 0xde, 0xde, 0xdf, 0xd7, 0xed, 0xdd, 0x7f, 0x33, 0x5e, 0x7e, 0xec, 0xc6, 0xe4, 0x65,
	0xf6, 0xd3, 0xf1, 0x02, 0xfb, 0x5d, 0x42, 0x38, 0x8d, 0x63, 0xfb, 0x4e, 0x99, 0x9d, 0x9f, 0x01,
	0xac, 0x2e, 0x5e, 0x08, 0xfa, 0x08, 0x6e, 0x59, 0xcf, 0x46, 0x23, 0xe7, 0xf8, 0xa4, 0x7b, 0x32,
	0x70, 0x9e, 0x8f, 0x8f, 0xad, 0xc1, 0xfe, 0xf0, 0x60, 0x38, 0xe8, 0xab, 0x85, 0x66, 0xe3, 0xe2,
	0x52, 0xaf, 0x8d, 0x59, 0x38, 0x98, 0x7b, 0xb1, 0xa0, 0xa1, 0x40, 0x1f, 0x42, 0xb4, 0x44, 0xb6,
	0x06, 0xe3, 0xfe, 0x70, 0xfc, 0x54, 0x05, 0xcd, 0xda, 0xc5, 0xa5, 0xbe, 0x6a, 0xd1, 0x90, 0x78,
	0xe1, 0x04, 0x3d, 0x84, 0x9b, 0x4b, 0xa4, 0xfd, 0x67, 0x47, 0xd6, 0x68, 0x70, 0x32, 0xe8, 0xab,
	0x4a, 0x73, 0xed, 0xe2, 0x52, 0xaf, 0xee, 0xe7, 0xfb, 0x8f, 0xee, 0xc1, 0x8d, 0x25, 0xe2, 0x41,
	0x77, 0x38, 0x1a, 0xf4, 0xd5, 0x62, 0x13, 0x5e, 0x5c, 0xea, 0xe5, 0x03, 0xec, 0xf9, 0x94, 0x34,
	0x2b, 0x5f, 0xff, 0xd0, 0x2a, 0xfc, 0xf4, 0x63, 0x0b, 0xf4, 0xec, 0xab, 0xbf, 0x5a, 0x85, 0xab,
	0x9b, 0x16, 0x78, 0x7d, 0xd3, 0x02, 0x7f, 0xde, 0xb4, 0xc0, 0x37, 0xb7, 0xad, 0xc2, 0xeb, 0xdb,
	0x56, 0xe1, 0xf7, 0xdb, 0x56, 0xe1, 0x8b, 0x4f, 0x96, 0x0c, 0x49, 0x9f, 0x46, 0x48, 0xc5, 0x2b,
	0xc6, 0x5f, 0x66, 0xd1, 0xae, 0xcb, 0x38, 0x35, 0xe7, 0x77, 0xff, 0x03, 0x4e, 0xcb, 0xc9, 0x08,
	0x3f, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xf4, 0x9a, 0xca, 0x22, 0x06, 0x00, 0x00,
}

func (m *PollMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PollMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PollMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ModuleMetadata != nil {
		{
			size, err := m.ModuleMetadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if len(m.Module) > 0 {
		i -= len(m.Module)
		copy(dAtA[i:], m.Module)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Module)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	{
		size, err := m.Snapshot.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x7a
	if m.ID != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x68
	}
	if m.CompletedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CompletedAt))
		i--
		dAtA[i] = 0x60
	}
	if m.GracePeriod != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.GracePeriod))
		i--
		dAtA[i] = 0x58
	}
	if len(m.RewardPoolName) > 0 {
		i -= len(m.RewardPoolName)
		copy(dAtA[i:], m.RewardPoolName)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RewardPoolName)))
		i--
		dAtA[i] = 0x52
	}
	if m.MinVoterCount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MinVoterCount))
		i--
		dAtA[i] = 0x38
	}
	if m.State != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x30
	}
	{
		size, err := m.VotingThreshold.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Result != nil {
		{
			size, err := m.Result.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.ExpiresAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ExpiresAt))
		i--
		dAtA[i] = 0x18
	}
	return len(dAtA) - i, nil
}

func (m *PollKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PollKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PollKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Module) > 0 {
		i -= len(m.Module)
		copy(dAtA[i:], m.Module)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Module)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Vote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Vote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Vote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Result != nil {
		{
			size, err := m.Result.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ResultsDeprecated) > 0 {
		for iNdEx := len(m.ResultsDeprecated) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ResultsDeprecated[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *PollParticipants) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PollParticipants) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PollParticipants) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Participants) > 0 {
		for iNdEx := len(m.Participants) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Participants[iNdEx])
			copy(dAtA[i:], m.Participants[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.Participants[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.PollID != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.PollID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PollMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ExpiresAt != 0 {
		n += 1 + sovTypes(uint64(m.ExpiresAt))
	}
	if m.Result != nil {
		l = m.Result.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.VotingThreshold.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.State != 0 {
		n += 1 + sovTypes(uint64(m.State))
	}
	if m.MinVoterCount != 0 {
		n += 1 + sovTypes(uint64(m.MinVoterCount))
	}
	l = len(m.RewardPoolName)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.GracePeriod != 0 {
		n += 1 + sovTypes(uint64(m.GracePeriod))
	}
	if m.CompletedAt != 0 {
		n += 1 + sovTypes(uint64(m.CompletedAt))
	}
	if m.ID != 0 {
		n += 1 + sovTypes(uint64(m.ID))
	}
	l = m.Snapshot.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = len(m.Module)
	if l > 0 {
		n += 2 + l + sovTypes(uint64(l))
	}
	if m.ModuleMetadata != nil {
		l = m.ModuleMetadata.Size()
		n += 2 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *PollKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Module)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *Vote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ResultsDeprecated) > 0 {
		for _, e := range m.ResultsDeprecated {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.Result != nil {
		l = m.Result.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *PollParticipants) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PollID != 0 {
		n += 1 + sovTypes(uint64(m.PollID))
	}
	if len(m.Participants) > 0 {
		for _, b := range m.Participants {
			l = len(b)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PollMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PollMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PollMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			m.ExpiresAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Result == nil {
				m.Result = &types.Any{}
			}
			if err := m.Result.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingThreshold", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VotingThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= PollState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinVoterCount", wireType)
			}
			m.MinVoterCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinVoterCount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardPoolName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardPoolName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GracePeriod", wireType)
			}
			m.GracePeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GracePeriod |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedAt", wireType)
			}
			m.CompletedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompletedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= PollID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Snapshot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Snapshot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Module = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleMetadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ModuleMetadata == nil {
				m.ModuleMetadata = &types.Any{}
			}
			if err := m.ModuleMetadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PollKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PollKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PollKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Module = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Vote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Vote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Vote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultsDeprecated", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResultsDeprecated = append(m.ResultsDeprecated, &types.Any{})
			if err := m.ResultsDeprecated[len(m.ResultsDeprecated)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Result == nil {
				m.Result = &types.Any{}
			}
			if err := m.Result.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PollParticipants) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PollParticipants: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PollParticipants: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PollID", wireType)
			}
			m.PollID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PollID |= PollID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participants", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participants = append(m.Participants, make([]byte, postIndex-iNdEx))
			copy(m.Participants[len(m.Participants)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
