name: Build and push rosetta docker image

on:
  push:
    branches:
      - v0.14.1-rosetta

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        arch: [amd64]

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          ref: v0.14.1-rosetta
          submodules: recursive

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Set up ssh agent
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.CICD_RSA_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          config: .github/buildkit-config.toml

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME_ROS }}
          password: ${{ secrets.DOCKER_HUB_TOKEN_ROS }}

      - name: Build and push docker image for all platforms
        run: |
          make build-push-docker-images-rosetta
        env:
          SEMVER: v0.14.1-rosetta

      - name: Sign the images with GitHub OIDC
        run: cosign sign --oidc-issuer https://token.actions.githubusercontent.com ${TAGS}
        env:
          TAGS: tototesteur/axelar-core:v0.14.1-rosetta
          COSIGN_EXPERIMENTAL: 1
