name: Synchronize to private repo

on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
        fetch-depth: 0

    - name: Add private repo as a remote
      run: git remote add private ${{ secrets.PRIVATE_REPO_URL }}

    - name: Fetch all history from origin
      run: git fetch origin --prune

    - name: Push everything to private repo
      run: git push private --all && git push private --tags
