name: Synchronize to private repo

on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout axelar-core
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
        fetch-depth: 0

    - name: Sync with private repo
      run: |


        # Add private repo as a remote
        git remote add private ${{ secrets.PRIVATE_REPO_URL }}

        # Fetch branches from private repo
        git fetch private

        # Push main branch to private repo
        # git reset --hard origin/main
        # git push private main --force

        # Push release branches to private repo
        for branch in $(git branch -r | grep 'origin/releases/'); do
          git checkout -b ${branch#origin/} || git checkout ${branch#origin/}
          git push private ${branch#origin/} --force
        done