name: Synchronize to private repo

on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
        fetch-depth: 0

    - name: Sync with private repo
      run: |
        # Set the push URL for the 'origin' remote
        git remote set-url --push origin ${{ secrets.PRIVATE_REPO_URL }}
        # Push changes using --mirror, excluding the deletion of the main branch
        git push --mirror --no-thin --prune
