name: Test combine

on:
  push:
    branches:
      - "feat/test-combine"

jobs:
  combine-sign:

    needs: release-docker
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull images
        run: |
          docker pull axelarnet/axelar-core-linux-arm64:${SEMVER} \
          docker pull axelarnet/axelar-core-linux-amd64:${SEMVER} \
          docker pull axelarnet/axelar-core-linux-armv6:${SEMVER} \
          docker pull axelarnet/axelar-core-linux-armv7:${SEMVER}
        env:
          SEMVER: v0.31.1

      - name: Create multiarch manifest
        run: |
          docker manifest create axelarnet/axelar-core:${SEMVER} \
          axelarnet/axelar-core-linux-arm64:${SEMVER} \
          axelarnet/axelar-core-linux-amd64:${SEMVER} \
          axelarnet/axelar-core-linux-armv6:${SEMVER} \
          axelarnet/axelar-core-linux-armv7:${SEMVER}
        env:
          SEMVER: v0.31.1
